name: Update Submodules
on:
  workflow_dispatch:
  repository_dispatch:
    types: [blog]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Submodule
        run: git submodule update --remote
      - name: Push Changes
        uses: EndBug/add-and-commit@v5
        with:
          add: '.gitmodules'
          author_name: 'Blog Updater'
          message: 'Updating blog submodule'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
