name: Update Submodules
on:
  workflow_dispatch:
  schedule:
    - cron: '0/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Submodule
        run: git submodule update --remote 
