name: Update Submodules
on:
  workflow_dispatch:
  repository_dispatch:
    types: [blog]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Update Submodule
        run: git submodule update --remote
      - name: Push Changes
        run: |
          git config user.name "Blog Updater"
          git config user.email "aidop@me.com"
          git add blog
          git commit -m "Auto-updated blog submodule"
          git push
        continue-on-error: true
